# Generated by Django 4.1 on 2022-08-23 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('repuesto', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado'), ('Pocas', 'Pocas')], default='Disponible', max_length=20, null=True)),
                ('cantidad', models.IntegerField()),
                ('entrada', models.CharField(max_length=20)),
                ('salida', models.CharField(max_length=20)),
                ('ocupacionenArea', models.CharField(max_length=100)),
                ('especificaciones', models.CharField(max_length=20)),
                ('imagenE', models.ImageField(null=True, upload_to='equipos')),
                ('marca', models.CharField(max_length=20)),
                ('valorU', models.FloatField(max_length=20)),
                ('costo', models.FloatField(max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('repuesto', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('cantidad', models.FloatField(max_length=20)),
                ('entrada', models.CharField(max_length=20)),
                ('salida', models.CharField(max_length=20)),
                ('ocupacionenArea', models.CharField(max_length=20)),
                ('especificaciones', models.CharField(max_length=100)),
                ('imagenH', models.ImageField(null=True, upload_to='herramientas')),
                ('marca', models.CharField(max_length=20)),
                ('valorU', models.FloatField(max_length=20)),
                ('costo', models.FloatField(max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Suministros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('repuesto', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('entrada', models.CharField(max_length=20)),
                ('salida', models.CharField(max_length=20)),
                ('ocupacionenArea', models.CharField(max_length=20)),
                ('especificaciones', models.CharField(max_length=100)),
                ('imagenS', models.ImageField(null=True, upload_to='suministros')),
                ('marca', models.CharField(max_length=20)),
                ('valorU', models.FloatField(max_length=20)),
                ('costo', models.FloatField(max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.equipos')),
                ('herramientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.herramientas')),
                ('suministros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.suministros')),
            ],
        ),
    ]
