# Generated by Django 4.1 on 2022-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='ocupacionenArea',
            field=models.CharField(choices=[('Linea Sulfurico', 'Linea Sulfurico'), ('Linea Sulfurico 2', 'Linea Sulfurico 2'), ('Linea Fosforico', 'Linea Fosforico'), ('Linea Fosforita', 'Linea Fosforita'), ('Linea D', 'Linea D'), ('Linea Mantenimiento', 'Linea Mantenimiento'), ('Linea Raymon', 'Linea Raymon'), ('Linea Mezclas', 'Linea Mezclas'), ('Linea Horno', 'Linea Horno'), ('Linea Dolomita', 'Linea Dolomita')], default='Linea Sulfurico', max_length=20, null=True),
        ),
    ]
