# Generated by Django 4.1 on 2022-08-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_equipos_fecha_alter_herramientas_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='cantidad',
            field=models.FloatField(max_length=20),
        ),
    ]
