# Generated by Django 4.1 on 2022-08-23 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_equipos_ocupacionenarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
